### Compose state dicts to be used in composite models

In [1]:
!pwd

/home/tucker/sabbatical/predict_bert_embeddings/char_lm/char_seq_to_masked_emb


In [2]:
import torch

In [3]:
# module to predict embeddings from character sequences
exphash_emb = '70757d8a7'
sd = torch.load('../single_emb_pred/models/%s'%exphash_emb)

FileNotFoundError: [Errno 2] No such file or directory: '../single_emb_pred/models/70757d8a7'

In [14]:
# attention module to predict the start of a token
exphash_attn = '81270f4d8'
sd2 = torch.load('../token_start_pred/models/%s'%exphash_attn)

In [15]:
sd.update(sd2)

In [16]:
new = sd.__class__()

In [17]:
src = []
dst = []

In [18]:
src_dst_map = {k:dst[i] for i, k in enumerate(src)}

In [19]:
src_dst_map = {}

In [20]:
for k, v in sd.items():
  new_name = 'char_embedder.' + k
  if new_name in src_dst_map:
    new_name = src_dst_map[new_name]
  new[new_name] = v


In [21]:
new.keys()

odict_keys(['char_embedder.tokens_to_emb.emb.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.bias', 'char_embedder.tokens_to_emb.segment2.convs.4.weight', 'char_embedder.tokens_to_emb.segment2.convs.4.bias', 'char_embedder.tokens_to_emb.segment2.convs.7.weight', 'char_embedder.tokens_to_emb.segment2.convs.7.bias', 'char_embedder.tokens_to_emb.final_conv.weight', 'char_embedder.tokens_to_emb.final_conv.bias', 'char_embedder.tokens_start_attn.emb.weight', 'char_embedder.tokens_start_attn.conv.convs.1.weight', 'char_embedder.tokens_start_attn.conv.convs.1.bias', 'char_embedder.tokens_start_attn.conv.convs.4.weight', 'char_embedder.tokens_start_attn.conv.convs.4.bias', 'char_embedder.tokens_start_attn.conv.convs.7.weight', 'char_embedder.tokens_start_attn.conv.convs.7.bias', 'char_embedder.tokens_start_attn.conv.convs.10.weight', 'char_embedder.tokens_start_attn.conv.convs.10.bias', 'char_embedder.tokens_start_attn.final_conv.we

In [22]:
filename = 'models/%s+%s'%(exphash_emb, exphash_attn)
torch.save(new, filename)
filename

'models/3300e8546+81270f4d8'

In [17]:
filename = 'models/%s'%(exphash_emb)
torch.save(new, filename)
filename

'models/7c7001396'

In [4]:
distilbert_orig = torch.load('bert_distil_uncased/pytorch_model.bin')

In [7]:
masked_tok2tok_fine_tuned = torch.load('models/aa082d878')

In [15]:
for k in distilbert_orig.keys():
  if "bert."+k not in masked_tok2tok_fine_tuned:
    print(k)

In [16]:
for k in masked_tok2tok_fine_tuned.keys():
  k = k.replace('bert.d', 'd')
  if k not in distilbert_orig:
    print(k)

bert.vocab_transform.weight
bert.vocab_transform.bias
bert.vocab_layer_norm.weight
bert.vocab_layer_norm.bias
bert.vocab_projector.weight
bert.vocab_projector.bias


In [ ]:
masked_tok2tok_fine_tuned

In [27]:
new = masked_tok2tok_fine_tuned.__class__()

In [28]:
for k, v in masked_tok2tok_fine_tuned.items():
  new_name =  k.replace('bert.d', 'd').replace('bert.v', 'v')
  new[new_name] = v

In [29]:
torch.save(new, 'bert_distil_dense_out/pytorch_model.bin')

In [30]:
new.keys()

odict_keys(['distilbert.embeddings.word_embeddings.weight', 'distilbert.embeddings.position_embeddings.weight', 'distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias', 'distilbert.transformer.layer.0.attention.q_lin.weight', 'distilbert.transformer.layer.0.attention.q_lin.bias', 'distilbert.transformer.layer.0.attention.k_lin.weight', 'distilbert.transformer.layer.0.attention.k_lin.bias', 'distilbert.transformer.layer.0.attention.v_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.bias', 'distilbert.transformer.layer.0.attention.out_lin.weight', 'distilbert.transformer.layer.0.attention.out_lin.bias', 'distilbert.transformer.layer.0.sa_layer_norm.weight', 'distilbert.transformer.layer.0.sa_layer_norm.bias', 'distilbert.transformer.layer.0.ffn.lin1.weight', 'distilbert.transformer.layer.0.ffn.lin1.bias', 'distilbert.transformer.layer.0.ffn.lin2.weight', 'distilbert.transformer.layer.0.ffn.lin2.bias', 'distilbert.transformer.layer.0.output_layer_norm.

In [65]:
exphash_attn = ''
sd3 = torch.load('models/70757d8a7+b8d7b7834')

In [47]:
sd3.keys()

odict_keys(['char_embedder.tokens_to_emb.emb.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.bias', 'char_embedder.tokens_to_emb.segment2.convs.4.weight', 'char_embedder.tokens_to_emb.segment2.convs.4.bias', 'char_embedder.tokens_to_emb.segment2.convs.7.weight', 'char_embedder.tokens_to_emb.segment2.convs.7.bias', 'char_embedder.tokens_to_emb.segment2.convs.10.weight', 'char_embedder.tokens_to_emb.segment2.convs.10.bias', 'char_embedder.tokens_to_emb.final_conv.weight', 'char_embedder.tokens_to_emb.final_conv.bias', 'char_embedder.tokens_start_attn.emb.weight', 'char_embedder.tokens_start_attn.conv.convs.1.weight', 'char_embedder.tokens_start_attn.conv.convs.1.bias', 'char_embedder.tokens_start_attn.conv.convs.4.weight', 'char_embedder.tokens_start_attn.conv.convs.4.bias', 'char_embedder.tokens_start_attn.conv.convs.7.weight', 'char_embedder.tokens_start_attn.conv.convs.7.bias', 'char_embedder.tokens_start_attn.conv.convs.10

In [48]:
idx_to_char_map = {v:k for k,v in torch.load('../data/char_to_idx_map.pt').items()}
char_to_idx_map = torch.load('../data/char_to_idx_map.pt')
char_to_idx_map2 = torch.load('../data/char_to_idx_map2.pt')

In [49]:
char1_to_char2_map = {}
for k,v in idx_to_char_map.items():
  char1_to_char2_map[k] = char_to_idx_map2[v]

In [50]:
permute = torch.tensor(list(zip(*sorted(char1_to_char2_map.items(), key=lambda x: x[0])))[1])

In [51]:
sd3['char_embedder.tokens_start_attn.emb.weight'] = sd3['char_embedder.tokens_start_attn.emb.weight'][permute]

In [52]:
torch.save(sd3, 'models/70757d8a7+b8d7b7834_chr2')

In [53]:
new = sd3.__class__()

In [54]:
for k in sd2.keys():
  name = 'char_embedder.' + k
  new[k] = sd3[name]

In [60]:
sd3['char_embedder.tokens_start_attn.emb.weight'][-3:]

tensor([[-0.0297, -0.6496,  0.1166,  0.9153, -0.6380,  1.0827, -0.3581,  1.5057],
        [-0.8719,  0.1173, -1.9053, -0.5261, -0.0899, -0.6353, -0.2218, -0.8624],
        [ 0.2686,  0.2809, -0.4896, -0.8134,  0.5294,  0.3006, -1.7901, -1.5006]],
       device='cuda:0')

In [67]:
new['tokens_start_attn.emb.weight'][-3:]

tensor([[ 0.0968, -1.1682, -0.9402,  1.3846,  0.0190, -1.0596, -0.5489,  0.1320],
        [ 0.4134,  0.1838, -0.9798,  0.5558, -0.7181, -1.9068,  1.7617,  0.5521],
        [-0.3987, -0.5849, -1.5584,  1.0910, -1.0673, -1.3522,  0.2754,  0.3640]],
       device='cuda:0')

In [68]:
torch.save(new, '../token_start_pred/models/b8d7b7834_chr2')

In [66]:
sd2['tokens_start_attn.emb.weight'][-3:]

tensor([[-0.0297, -0.6496,  0.1166,  0.9153, -0.6380,  1.0827, -0.3581,  1.5057],
        [-0.8719,  0.1173, -1.9053, -0.5261, -0.0899, -0.6353, -0.2218, -0.8624],
        [ 0.2686,  0.2809, -0.4896, -0.8134,  0.5294,  0.3006, -1.7901, -1.5006]],
       device='cuda:0')

In [6]:
sd3 = torch.load('models/70757d8a7+b8d7b7834')

In [7]:
sd2 = torch.load('../token_start_pred/models/81270f4d8')

In [8]:
sd3.keys()

odict_keys(['char_embedder.tokens_to_emb.emb.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.weight', 'char_embedder.tokens_to_emb.segment2.convs.1.bias', 'char_embedder.tokens_to_emb.segment2.convs.4.weight', 'char_embedder.tokens_to_emb.segment2.convs.4.bias', 'char_embedder.tokens_to_emb.segment2.convs.7.weight', 'char_embedder.tokens_to_emb.segment2.convs.7.bias', 'char_embedder.tokens_to_emb.segment2.convs.10.weight', 'char_embedder.tokens_to_emb.segment2.convs.10.bias', 'char_embedder.tokens_to_emb.final_conv.weight', 'char_embedder.tokens_to_emb.final_conv.bias', 'char_embedder.tokens_start_attn.emb.weight', 'char_embedder.tokens_start_attn.conv.convs.1.weight', 'char_embedder.tokens_start_attn.conv.convs.1.bias', 'char_embedder.tokens_start_attn.conv.convs.4.weight', 'char_embedder.tokens_start_attn.conv.convs.4.bias', 'char_embedder.tokens_start_attn.conv.convs.7.weight', 'char_embedder.tokens_start_attn.conv.convs.7.bias', 'char_embedder.tokens_start_attn.conv.convs.10

In [10]:
for k,v in sd3.items():
  name2 = k.replace("char_embedder.", "")
  if name2 in sd2:
    sd3[k] = sd2[name2]

In [11]:
torch.save(sd3, 'models/70757d8a7+81270f4d8')